version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Maps port 8080 on the host to port 8080 in the container
    environment:
      # Add any environment variables your application needs here
      SPRING_PROFILES_ACTIVE: production